### ISSUE TITLE
Port `app-lua` to use musl

### ISSUE THREAD

**Issue by StefanJum** [unikraft/app-lua#5]
Port `app-lua` to use [musl](https://github.com/unikraft/lib-musl), the new supported unikraft glibc.

You should create the `Makefile`  and `Makefile.uk` files.
You can find more information on this on [the Unikraft website](https://unikraft.org/docs/usage/make_build/#extending-the-build).
You can find a list of the external libraries the application depends on in the [`kraft.yaml` file, under the `libraries:` section](https://github.com/unikraft/app-lua/blob/staging/kraft.yaml#L11-L13).
You will need to replace the `newlib` dependency with `musl`.

Hackathon points: 40

**Comment by steliosdimb** [comment]
Working on this !

**Comment by razvand** [comment]
Solved by #6
